export enum SONGS {
  TRAIN_KEPT_A_ROLLIN = "Train Kept A-Rollin'",
  I_CANT_QUIT_YOU_BABY = "I Can't Quit You Baby",
  DAZED_AND_CONFUSED = "Dazed and Confused",
  HOW_MANY_MORE_TIMES = "How Many More Times",
  WHITE_SUMMER_BLACK_MOUNTAIN_SIDE = "White Summer / Black Mountain Side",
  FOR_YOUR_LOVE = "For Your Love",
  YOU_SHOOK_ME = "You Shook Me",
  BABE_IM_GONNA_LEAVE_YOU = "Babe I'm Gonna Leave You",
  AS_LONG_AS_I_HAVE_YOU = "As Long as I Have You",
  COMMUNICATION_BREAKDOWN = "Communication Breakdown",
  PATS_DELIGHT = "Pat's Delight",
  KILLING_FLOOR = "Killing Floor",
  I_GOTTA_MOVE = "I Gotta Move",
  SITTING_AND_THINKING = "Sitting and Thinking",
  WHOLE_LOTTA_LOVE = "Whole Lotta Love",
  LONG_TALL_SALLY = "Long Tall Sally",
  WHAT_IS_AND_WHAT_SHOULD_NEVER_BE = "What Is and What Should Never Be",
  YOUR_TIME_IS_GONNA_COME = "Your Time Is Gonna Come",
  GOOD_TIMES_BAD_TIMES = "Good Times Bad Times",
  HEARTBREAKER = "Heartbreaker",
  MOBY_DICK = "Moby Dick",
  CMON_EVERYBODY_SOMETHING_ELSE = "C'mon Everybody / Something Else",
  WERE_GONNA_GROOVE = "We're Gonna Groove",
  SINCE_IVE_BEEN_LOVING_YOU = "Since I've Been Loving You",
  THANK_YOU = "Thank You",
  BRING_IT_ON_HOME = "Bring It On Home",
  IMMIGRANT_SONG = "Immigrant Song",
  THATS_THE_WAY = "That's the Way",
  BRON_YR_AUR = "Bron-Yr-Aur",
  OUT_ON_THE_TILES = "Out On The Tiles",
  BLUEBERRY_HILL = "Blueberry Hill",
  BLACK_DOG = "Black Dog",
  STAIRWAY_TO_HEAVEN = "Stairway to Heaven",
  GOING_TO_CALIFORNIA = "Going to California",
  ROCK_AND_ROLL = "Rock and Roll",
  CELEBRATION_DAY = "Celebration Day",
  FOUR_STICKS = "Four Sticks",
  GALLOWS_POLE = "Gallows Pole",
  MISTY_MOUNTAIN_HOP = "Misty Mountain Hop",
  WEEKEND = "Weekend",
  WALK_DONT_RUN = "Walk Don't Run",
  BRON_YR_AUR_STOMP = "Bron-Yr-Aur Stomp",
  TANGERINE = "Tangerine",
  ITLL_BE_ME = "It'll Be Me",
  OVER_THE_HILLS_AND_FAR_AWAY = "Over the Hills and Far Away",
  BLACK_COUNTRY_WOMAN = "Black Country Woman",
  DANCING_DAYS = "Dancing Days",
  THE_OCEAN = "The Ocean",
  LOUIE_LOUIE = "Louie Louie",
  MONEY_THATS_WHAT_I_WANT = "Money (That's What I Want)",
  THE_SONG_REMAINS_THE_SAME = "The Song Remains the Same",
  THE_RAIN_SONG = "The Rain Song",
  STAND_BY_ME = "Stand By Me",
  NO_QUARTER = "No Quarter",
  SICK_AGAIN = "Sick Again",
  WHEN_THE_LEVEE_BREAKS = "When the Levee Breaks",
  IN_MY_TIME_OF_DYING = "In My Time of Dying",
  KASHMIR = "Kashmir",
  THE_WANTON_SONG = "The Wanton Song",
  TRAMPLED_UNDER_FOOT = "Trampled Under Foot",
  NOBODYS_FAULT_BUT_MINE = "Nobody's Fault but Mine",
  TEN_YEARS_GONE = "Ten Years Gone",
  THE_BATTLE_OF_EVERMORE = "The Battle of Evermore",
  ACHILLES_LAST_STAND = "Achilles Last Stand",
  HOT_DOG = "Hot Dog",
  IN_THE_EVENING = "In the Evening",
  ALL_MY_LOVE = "All My Love",
}

export interface ISong {
  name: SONGS;
  isException?: boolean;
  isEncore?: boolean;
}

export interface ITour {
  id: string;
  name: string;
  flag: string;
  year: number;
  shows: number;
  songs: ISong[];
}

const tours: ITour[] = [
  {
    id: "1c438916",
    name: "Scandinavia",
    flag: "🇩🇰",
    year: 1968,
    shows: 14,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.FOR_YOUR_LOVE },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU },
      { name: SONGS.AS_LONG_AS_I_HAVE_YOU },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
    ],
  },
  {
    id: "4081b991",
    name: "UK",
    flag: "🇬🇧",
    year: 1968,
    shows: 16,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.AS_LONG_AS_I_HAVE_YOU },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.FOR_YOUR_LOVE },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.PATS_DELIGHT },
      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
    ],
  },
  {
    id: "d7cd062b",
    name: "North America",
    flag: "🇺🇸",
    year: 1968,
    shows: 36,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.AS_LONG_AS_I_HAVE_YOU },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.PATS_DELIGHT },
      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.KILLING_FLOOR },
      { name: SONGS.FOR_YOUR_LOVE },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
    ],
  },
  {
    id: "cc92d399",
    name: "UK and Scandinavia",
    flag: "🇬🇧",
    year: 1969,
    shows: 33,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.I_GOTTA_MOVE, isException: true },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.AS_LONG_AS_I_HAVE_YOU },
      { name: SONGS.KILLING_FLOOR },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
      { name: SONGS.PATS_DELIGHT },
    ],
  },
  {
    id: "5bae02b1",
    name: "North America Spring",
    flag: "🇺🇸",
    year: 1969,
    shows: 28,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.AS_LONG_AS_I_HAVE_YOU, isException: true },
      { name: SONGS.KILLING_FLOOR },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.SITTING_AND_THINKING, isException: true },
      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
      { name: SONGS.PATS_DELIGHT },
      { name: SONGS.WHOLE_LOTTA_LOVE, isException: true },
    ],
  },
  {
    id: "2f99abe5",
    name: "UK Summer",
    flag: "🇬🇧",
    year: 1969,
    shows: 12,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.AS_LONG_AS_I_HAVE_YOU, isException: true },
      { name: SONGS.KILLING_FLOOR, isException: true },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU, isException: true },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.PATS_DELIGHT, isException: true },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
      { name: SONGS.LONG_TALL_SALLY, isException: true },
    ],
  },
  {
    id: "f8e69d0a",
    name: "North America Summer",
    flag: "🇺🇸",
    year: 1969,
    shows: 46,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.COMMUNICATION_BREAKDOWN },

      { name: SONGS.I_GOTTA_MOVE, isException: true },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE, isException: true },
      { name: SONGS.PATS_DELIGHT, isException: true },
      { name: SONGS.YOUR_TIME_IS_GONNA_COME, isException: true },
      { name: SONGS.LONG_TALL_SALLY, isException: true },
    ],
  },

  {
    id: "b3a29330",
    name: "Europe Autumn",
    flag: "🇪🇺",
    year: 1969,
    shows: 5,
    songs: [
      { name: SONGS.GOOD_TIMES_BAD_TIMES },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.HEARTBREAKER, isException: true },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE, isException: true },
      { name: SONGS.YOU_SHOOK_ME, isException: true },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE, isException: true },
      { name: SONGS.MOBY_DICK, isException: true },
      { name: SONGS.HOW_MANY_MORE_TIMES },
    ],
  },
  {
    id: "66d39321",
    name: "North America Autumn",
    flag: "🇺🇸",
    year: 1969,
    shows: 20,
    songs: [
      { name: SONGS.GOOD_TIMES_BAD_TIMES },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE, isException: true },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.HOW_MANY_MORE_TIMES },

      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU, isException: true },
      { name: SONGS.CMON_EVERYBODY_SOMETHING_ELSE, isException: true },
      { name: SONGS.WHOLE_LOTTA_LOVE, isException: true },
    ],
  },
  {
    id: "db1a04c4",
    name: "UK",
    flag: "🇬🇧",
    year: 1970,
    shows: 8,
    songs: [
      { name: SONGS.WERE_GONNA_GROOVE },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.THANK_YOU },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE, isException: true },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.HOW_MANY_MORE_TIMES },

      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.BRING_IT_ON_HOME, isEncore: true },
      { name: SONGS.LONG_TALL_SALLY, isEncore: true },
      { name: SONGS.CMON_EVERYBODY_SOMETHING_ELSE, isEncore: true },
    ],
  },
  {
    id: "9aa6948d",
    name: "Europe",
    flag: "🇪🇺",
    year: 1970,
    shows: 16,
    songs: [
      { name: SONGS.WERE_GONNA_GROOVE },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.THANK_YOU },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE, isException: true },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.HOW_MANY_MORE_TIMES },

      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.BRING_IT_ON_HOME, isEncore: true },
      { name: SONGS.LONG_TALL_SALLY, isEncore: true },
      { name: SONGS.CMON_EVERYBODY_SOMETHING_ELSE, isEncore: true },
    ],
  },
  {
    id: "72652df6",
    name: "North America Spring",
    flag: "🇺🇸",
    year: 1970,
    shows: 28,
    songs: [
      { name: SONGS.WERE_GONNA_GROOVE },
      { name: SONGS.I_CANT_QUIT_YOU_BABY, isException: true },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.BRING_IT_ON_HOME, isException: true },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.THANK_YOU },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.HOW_MANY_MORE_TIMES },

      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
    ],
  },
  {
    id: "b149df9d",
    name: "Iceland, Bath and Germany, Summer",
    flag: "🇩🇪",
    year: 1970,
    shows: 6,
    songs: [
      { name: SONGS.IMMIGRANT_SONG },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.BRING_IT_ON_HOME },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.THANK_YOU },
      { name: SONGS.THATS_THE_WAY },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.HOW_MANY_MORE_TIMES, isException: true },

      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.LONG_TALL_SALLY, isEncore: true },
    ],
  },
  {
    id: "153a0a8b",
    name: "North America Summer",
    flag: "🇺🇸",
    year: 1970,
    shows: 25,
    songs: [
      { name: SONGS.IMMIGRANT_SONG },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.BRING_IT_ON_HOME },
      { name: SONGS.THATS_THE_WAY },
      { name: SONGS.BRON_YR_AUR },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.THANK_YOU },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.WHOLE_LOTTA_LOVE },

      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.OUT_ON_THE_TILES, isEncore: true },
      { name: SONGS.HOW_MANY_MORE_TIMES, isEncore: true },
      { name: SONGS.TRAIN_KEPT_A_ROLLIN, isEncore: true },
      { name: SONGS.BLUEBERRY_HILL, isEncore: true },
    ],
  },
  {
    id: "5032689e",
    name: "UK Spring",
    flag: "🇬🇧",
    year: 1971,
    shows: 13,
    songs: [
      { name: SONGS.IMMIGRANT_SONG },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.STAIRWAY_TO_HEAVEN },
      { name: SONGS.GOING_TO_CALIFORNIA },
      { name: SONGS.THATS_THE_WAY },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.WHOLE_LOTTA_LOVE },

      { name: SONGS.THANK_YOU, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.ROCK_AND_ROLL, isEncore: true },
      { name: SONGS.BRING_IT_ON_HOME, isEncore: true },
    ],
  },
  {
    id: "fbf283f8",
    name: "Europe",
    flag: "🇪🇺",
    year: 1971,
    shows: 6,
    songs: [
      { name: SONGS.IMMIGRANT_SONG },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.STAIRWAY_TO_HEAVEN },
      { name: SONGS.GOING_TO_CALIFORNIA },
      { name: SONGS.THATS_THE_WAY },
      { name: SONGS.CELEBRATION_DAY, isException: true },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.MOBY_DICK, isException: true },
      { name: SONGS.FOUR_STICKS, isException: true },
      { name: SONGS.GALLOWS_POLE, isException: true },
      { name: SONGS.WHOLE_LOTTA_LOVE },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isException: true },
      { name: SONGS.MISTY_MOUNTAIN_HOP, isException: true },
      { name: SONGS.ROCK_AND_ROLL, isException: true },
      { name: SONGS.WEEKEND, isException: true },
    ],
  },
  {
    id: "0280df9f",
    name: "North America",
    flag: "🇺🇸",
    year: 1971,
    shows: 26,
    songs: [
      { name: SONGS.WALK_DONT_RUN, isException: true },
      { name: SONGS.IMMIGRANT_SONG },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.STAIRWAY_TO_HEAVEN },
      { name: SONGS.CELEBRATION_DAY },
      { name: SONGS.THATS_THE_WAY },
      { name: SONGS.GOING_TO_CALIFORNIA },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.WHOLE_LOTTA_LOVE },

      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.THANK_YOU, isEncore: true },
      { name: SONGS.ROCK_AND_ROLL, isEncore: true },
      { name: SONGS.WEEKEND, isEncore: true },
    ],
  },
  {
    id: "64f26790",
    name: "Japan",
    flag: "🇯🇵",
    year: 1971,
    shows: 5,
    songs: [
      { name: SONGS.IMMIGRANT_SONG },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.STAIRWAY_TO_HEAVEN },
      { name: SONGS.CELEBRATION_DAY },
      { name: SONGS.BRON_YR_AUR_STOMP },
      { name: SONGS.THATS_THE_WAY },
      { name: SONGS.GOING_TO_CALIFORNIA },
      { name: SONGS.TANGERINE },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.WHOLE_LOTTA_LOVE },

      { name: SONGS.THANK_YOU, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.ROCK_AND_ROLL, isEncore: true },
    ],
  },
  {
    id: "78a66401",
    name: "UK Winter",
    flag: "🇬🇧",
    year: 1971,
    shows: 16,
    songs: [
      { name: SONGS.IMMIGRANT_SONG },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.ROCK_AND_ROLL },
      { name: SONGS.STAIRWAY_TO_HEAVEN },
      { name: SONGS.GOING_TO_CALIFORNIA },
      { name: SONGS.THATS_THE_WAY },
      { name: SONGS.TANGERINE },
      { name: SONGS.BRON_YR_AUR_STOMP },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.CELEBRATION_DAY },
      { name: SONGS.MOBY_DICK, isException: true },
      { name: SONGS.WHOLE_LOTTA_LOVE },

      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.THANK_YOU, isEncore: true },
      { name: SONGS.GALLOWS_POLE, isEncore: true },
      { name: SONGS.WEEKEND, isEncore: true },
      { name: SONGS.ITLL_BE_ME, isEncore: true },
    ],
  },
  {
    id: "6c258045",
    name: "Australasia",
    flag: "🇦🇺",
    year: 1972,
    shows: 6,
    songs: [
      { name: SONGS.IMMIGRANT_SONG },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.CELEBRATION_DAY, isException: true },
      { name: SONGS.STAIRWAY_TO_HEAVEN },
      { name: SONGS.GOING_TO_CALIFORNIA },
      { name: SONGS.THATS_THE_WAY },
      { name: SONGS.TANGERINE },
      { name: SONGS.BRON_YR_AUR_STOMP },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.ROCK_AND_ROLL },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.WHOLE_LOTTA_LOVE },

      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.THANK_YOU, isEncore: true },
    ],
  },
  {
    id: "19d9dc2a",
    name: "North America",
    flag: "🇺🇸",
    year: 1972,
    shows: 21,
    songs: [
      { name: SONGS.IMMIGRANT_SONG },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.CELEBRATION_DAY, isException: true },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.OVER_THE_HILLS_AND_FAR_AWAY, isException: true },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.STAIRWAY_TO_HEAVEN },
      { name: SONGS.GOING_TO_CALIFORNIA },
      { name: SONGS.BLACK_COUNTRY_WOMAN, isException: true },
      { name: SONGS.THATS_THE_WAY },
      { name: SONGS.TANGERINE },
      { name: SONGS.BRON_YR_AUR_STOMP },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.DANCING_DAYS, isException: true },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.WHOLE_LOTTA_LOVE },

      { name: SONGS.ROCK_AND_ROLL, isEncore: true },
      { name: SONGS.THE_OCEAN, isEncore: true },
      { name: SONGS.LOUIE_LOUIE, isEncore: true },
      { name: SONGS.THANK_YOU, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.BRING_IT_ON_HOME, isEncore: true },
      { name: SONGS.MONEY_THATS_WHAT_I_WANT, isEncore: true },
      { name: SONGS.WEEKEND, isEncore: true },
    ],
  },
  {
    id: "6705b5de",
    name: "Japan",
    flag: "🇯🇵",
    year: 1972,
    shows: 6,
    songs: [
      { name: SONGS.ROCK_AND_ROLL },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.OVER_THE_HILLS_AND_FAR_AWAY },
      { name: SONGS.MISTY_MOUNTAIN_HOP },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.DANCING_DAYS },
      { name: SONGS.BRON_YR_AUR_STOMP },
      { name: SONGS.THE_SONG_REMAINS_THE_SAME },
      { name: SONGS.THE_RAIN_SONG },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.STAIRWAY_TO_HEAVEN },
      { name: SONGS.MOBY_DICK, isException: true },
      { name: SONGS.WHOLE_LOTTA_LOVE },

      { name: SONGS.HEARTBREAKER, isEncore: true },
      { name: SONGS.IMMIGRANT_SONG, isEncore: true },
      { name: SONGS.THANK_YOU, isEncore: true },
      { name: SONGS.THE_OCEAN, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.STAND_BY_ME, isEncore: true },
    ],
  },
  {
    id: "638f291f",
    name: "UK",
    flag: "🇬🇧",
    year: 1972,
    shows: 28,
    songs: [
      { name: SONGS.ROCK_AND_ROLL },
      { name: SONGS.OVER_THE_HILLS_AND_FAR_AWAY },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.MISTY_MOUNTAIN_HOP },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.DANCING_DAYS },
      { name: SONGS.BRON_YR_AUR_STOMP },
      { name: SONGS.THE_SONG_REMAINS_THE_SAME },
      { name: SONGS.THE_RAIN_SONG },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.STAIRWAY_TO_HEAVEN },
      { name: SONGS.WHOLE_LOTTA_LOVE },
      { name: SONGS.HOW_MANY_MORE_TIMES, isException: true },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE, isException: true },

      { name: SONGS.HEARTBREAKER, isEncore: true },
      { name: SONGS.IMMIGRANT_SONG, isEncore: true },
      { name: SONGS.THANK_YOU, isEncore: true },
      { name: SONGS.THE_OCEAN, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
    ],
  },
  {
    id: "5737b1f6",
    name: "Europe",
    flag: "🇪🇺",
    year: 1973,
    shows: 21,
    songs: [
      { name: SONGS.ROCK_AND_ROLL },
      { name: SONGS.OVER_THE_HILLS_AND_FAR_AWAY },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.MISTY_MOUNTAIN_HOP },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.DANCING_DAYS },
      { name: SONGS.BRON_YR_AUR_STOMP },
      { name: SONGS.THE_SONG_REMAINS_THE_SAME },
      { name: SONGS.THE_RAIN_SONG },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.STAIRWAY_TO_HEAVEN },
      { name: SONGS.WHOLE_LOTTA_LOVE },

      { name: SONGS.HEARTBREAKER, isEncore: true },
      { name: SONGS.THE_OCEAN, isEncore: true },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE, isEncore: true },
    ],
  },
  {
    id: "da0ea5a6",
    name: "North America",
    flag: "🇺🇸",
    year: 1973,
    shows: 37,
    songs: [
      { name: SONGS.ROCK_AND_ROLL },
      { name: SONGS.CELEBRATION_DAY },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.OVER_THE_HILLS_AND_FAR_AWAY },
      { name: SONGS.MISTY_MOUNTAIN_HOP },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.NO_QUARTER },
      { name: SONGS.THE_SONG_REMAINS_THE_SAME },
      { name: SONGS.THE_RAIN_SONG },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.STAIRWAY_TO_HEAVEN },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.WHOLE_LOTTA_LOVE },

      { name: SONGS.THE_OCEAN, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.DANCING_DAYS, isEncore: true },
      { name: SONGS.THANK_YOU, isEncore: true },
    ],
  },
  {
    id: "99e6b319",
    name: "North America",
    flag: "🇺🇸",
    year: 1975,
    shows: 39,
    songs: [
      { name: SONGS.ROCK_AND_ROLL },
      { name: SONGS.SICK_AGAIN },
      { name: SONGS.OVER_THE_HILLS_AND_FAR_AWAY },
      { name: SONGS.WHEN_THE_LEVEE_BREAKS },
      { name: SONGS.IN_MY_TIME_OF_DYING },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.THE_SONG_REMAINS_THE_SAME },
      { name: SONGS.THE_RAIN_SONG },
      { name: SONGS.KASHMIR },
      { name: SONGS.THE_WANTON_SONG },
      { name: SONGS.NO_QUARTER },
      { name: SONGS.TRAMPLED_UNDER_FOOT },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.HOW_MANY_MORE_TIMES, isException: true },
      { name: SONGS.DAZED_AND_CONFUSED, isException: true },
      { name: SONGS.STAIRWAY_TO_HEAVEN },

      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.BLACK_DOG, isEncore: true },
      { name: SONGS.HEARTBREAKER, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
    ],
  },
  {
    id: "0f895006",
    name: "Earls Court",
    flag: "🇬🇧",
    year: 1975,
    shows: 5,
    songs: [
      { name: SONGS.ROCK_AND_ROLL },
      { name: SONGS.SICK_AGAIN },
      { name: SONGS.OVER_THE_HILLS_AND_FAR_AWAY },
      { name: SONGS.IN_MY_TIME_OF_DYING },
      { name: SONGS.THE_SONG_REMAINS_THE_SAME },
      { name: SONGS.THE_RAIN_SONG },
      { name: SONGS.KASHMIR },
      { name: SONGS.NO_QUARTER },
      { name: SONGS.TANGERINE },
      { name: SONGS.GOING_TO_CALIFORNIA },
      { name: SONGS.THATS_THE_WAY },
      { name: SONGS.BRON_YR_AUR_STOMP },
      { name: SONGS.TRAMPLED_UNDER_FOOT },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.STAIRWAY_TO_HEAVEN },

      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.BLACK_DOG, isEncore: true },
      { name: SONGS.HEARTBREAKER, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
    ],
  },
  {
    id: "6f969be0",
    name: "North America",
    flag: "🇺🇸",
    year: 1977,
    shows: 44,
    songs: [
      { name: SONGS.THE_SONG_REMAINS_THE_SAME },
      { name: SONGS.SICK_AGAIN },
      { name: SONGS.NOBODYS_FAULT_BUT_MINE },
      { name: SONGS.IN_MY_TIME_OF_DYING, isException: true },
      { name: SONGS.OVER_THE_HILLS_AND_FAR_AWAY, isException: true },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.NO_QUARTER },
      { name: SONGS.TEN_YEARS_GONE },
      { name: SONGS.THE_BATTLE_OF_EVERMORE },
      { name: SONGS.GOING_TO_CALIFORNIA },
      { name: SONGS.DANCING_DAYS, isException: true },
      { name: SONGS.BRON_YR_AUR_STOMP, isException: true },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.KASHMIR },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.ACHILLES_LAST_STAND },
      { name: SONGS.STAIRWAY_TO_HEAVEN },

      { name: SONGS.ROCK_AND_ROLL, isEncore: true },
      { name: SONGS.TRAMPLED_UNDER_FOOT, isEncore: true },
      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.BLACK_DOG, isEncore: true },
      { name: SONGS.HEARTBREAKER, isEncore: true },
      { name: SONGS.ITLL_BE_ME, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
    ],
  },
  {
    id: "0081cd06",
    name: "Knebworth",
    flag: "🇬🇧",
    year: 1979,
    shows: 2,
    songs: [
      { name: SONGS.THE_SONG_REMAINS_THE_SAME },
      { name: SONGS.CELEBRATION_DAY },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.NOBODYS_FAULT_BUT_MINE },
      { name: SONGS.OVER_THE_HILLS_AND_FAR_AWAY },
      { name: SONGS.MISTY_MOUNTAIN_HOP },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.NO_QUARTER },
      { name: SONGS.TEN_YEARS_GONE },
      { name: SONGS.HOT_DOG },
      { name: SONGS.THE_RAIN_SONG },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.KASHMIR },
      { name: SONGS.TRAMPLED_UNDER_FOOT },
      { name: SONGS.SICK_AGAIN },
      { name: SONGS.ACHILLES_LAST_STAND },
      { name: SONGS.IN_THE_EVENING },
      { name: SONGS.STAIRWAY_TO_HEAVEN },

      { name: SONGS.ROCK_AND_ROLL, isEncore: true },
      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.HEARTBREAKER, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
    ],
  },
  {
    id: "cd2f5117",
    name: "Europe",
    flag: "🇪🇺",
    year: 1980,
    shows: 14,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.NOBODYS_FAULT_BUT_MINE },
      { name: SONGS.BLACK_DOG },
      { name: SONGS.IN_THE_EVENING },
      { name: SONGS.THE_RAIN_SONG },
      { name: SONGS.HOT_DOG },
      { name: SONGS.ALL_MY_LOVE },
      { name: SONGS.TRAMPLED_UNDER_FOOT },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.ACHILLES_LAST_STAND },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.KASHMIR },
      { name: SONGS.STAIRWAY_TO_HEAVEN },

      { name: SONGS.ROCK_AND_ROLL, isEncore: true },
      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.HEARTBREAKER, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.MONEY_THATS_WHAT_I_WANT, isEncore: true },
    ],
  },
];

export default tours;
