const SONGS = {
  TRAIN_KEPT_A_ROLLIN: "Train Kept A-Rollin'",
  I_CANT_QUIT_YOU_BABY: "I Can't Quit You Baby",
  DAZED_AND_CONFUSED: "Dazed and Confused",
  HOW_MANY_MORE_TIMES: "How Many More Times",
  WHITE_SUMMER_BLACK_MOUNTAIN_SIDE: "White Summer / Black Mountain Side",
  FOR_YOUR_LOVE: "For Your Love",
  YOU_SHOOK_ME: "You Shook Me",
  BABE_IM_GONNA_LEAVE_YOU: "Babe I'm Gonna Leave You",
  AS_LONG_AS_I_HAVE_YOU: "As Long as I Have You",
  COMMUNICATION_BREAKDOWN: "Communication Breakdown",
  PATS_DELIGHT: "Pat's Delight",
  KILLING_FLOOR: "Killing Floor",
  I_GOTTA_MOVE: "I Gotta Move",
  SITTING_AND_THINKING: "Sitting and Thinking",
  WHOLE_LOTTA_LOVE: "Whole Lotta Love",
  LONG_TALL_SALLY: "Long Tall Sally",
  WHAT_IS_AND_WHAT_SHOULD_NEVER_BE: "What Is and What Should Never Be",
  YOUR_TIME_IS_GONNA_COME: "Your Time Is Gonna Come",
  GOOD_TIMES_BAD_TIMES: "Good Times Bad Times",
  HEARTBREAKER: "Heartbreaker",
  MOBY_DICK: "Moby Dick",
  CMON_EVERYBODY_SOMETHING_ELSE: "C'mon Everybody / Something Else",
  WERE_GONNA_GROOVE: "We're Gonna Groove",
  SINCE_IVE_BEEN_LOVING_YOU: "Since I've Been Loving You",
  THANK_YOU: "Thank You",
  BRING_IT_ON_HOME: "Bring It On Home",
  IMMIGRANT_SONG: "Immigrant Song",
  THATS_THE_WAY: "That's the Way",
  BRON_YR_AUR: "Bron Yr Aur",
  OUT_ON_THE_TILES: "Out On The Tiles",
  BLUEBERRY_HILL: "Blueberry Hill",
};

export interface ISong {
  name: string;
  isException?: boolean;
  isEncore?: boolean;
}

export interface ITour {
  id: string;
  name: string;
  flag: string;
  year: number;
  shows: number;
  songs: ISong[];
}

const tours: ITour[] = [
  {
    id: "1c438916",
    name: "Scandinavian",
    flag: "🇩🇰",
    year: 1968,
    shows: 14,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.FOR_YOUR_LOVE },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU },
      { name: SONGS.AS_LONG_AS_I_HAVE_YOU },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
    ],
  },
  {
    id: "4081b991",
    name: "UK",
    flag: "🇬🇧",
    year: 1968,
    shows: 16,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.AS_LONG_AS_I_HAVE_YOU },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.FOR_YOUR_LOVE },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.PATS_DELIGHT },
      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
    ],
  },
  {
    id: "d7cd062b",
    name: "North American",
    flag: "🇺🇸",
    year: 1968,
    shows: 36,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.AS_LONG_AS_I_HAVE_YOU },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.PATS_DELIGHT },
      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.KILLING_FLOOR },
      { name: SONGS.FOR_YOUR_LOVE },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
    ],
  },
  {
    id: "cc92d399",
    name: "UK and Scandinavian",
    flag: "🇬🇧",
    year: 1969,
    shows: 33,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.I_GOTTA_MOVE, isException: true },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.AS_LONG_AS_I_HAVE_YOU },
      { name: SONGS.KILLING_FLOOR },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
      { name: SONGS.PATS_DELIGHT },
    ],
  },
  {
    id: "5bae02b1",
    name: "North American Spring",
    flag: "🇺🇸",
    year: 1969,
    shows: 28,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.AS_LONG_AS_I_HAVE_YOU, isException: true },
      { name: SONGS.KILLING_FLOOR },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.SITTING_AND_THINKING, isException: true },
      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
      { name: SONGS.PATS_DELIGHT },
      { name: SONGS.WHOLE_LOTTA_LOVE, isException: true },
    ],
  },
  {
    id: "2f99abe5",
    name: "UK Summer",
    flag: "🇬🇧",
    year: 1969,
    shows: 12,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.AS_LONG_AS_I_HAVE_YOU, isException: true },
      { name: SONGS.KILLING_FLOOR, isException: true },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU, isException: true },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.PATS_DELIGHT, isException: true },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
      { name: SONGS.LONG_TALL_SALLY, isException: true },
    ],
  },
  {
    id: "f8e69d0a",
    name: "North American Summer",
    flag: "🇺🇸",
    year: 1969,
    shows: 46,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.COMMUNICATION_BREAKDOWN },

      { name: SONGS.I_GOTTA_MOVE, isException: true },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE, isException: true },
      { name: SONGS.PATS_DELIGHT, isException: true },
      { name: SONGS.YOUR_TIME_IS_GONNA_COME, isException: true },
      { name: SONGS.LONG_TALL_SALLY, isException: true },
    ],
  },

  {
    id: "b3a29330",
    name: "European Autumn",
    flag: "🇪🇺",
    year: 1969,
    shows: 5,
    songs: [
      { name: SONGS.GOOD_TIMES_BAD_TIMES },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.HEARTBREAKER, isException: true },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE, isException: true },
      { name: SONGS.YOU_SHOOK_ME, isException: true },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE, isException: true },
      { name: SONGS.MOBY_DICK, isException: true },
      { name: SONGS.HOW_MANY_MORE_TIMES },
    ],
  },
  {
    id: "66d39321",
    name: "North American Autumn",
    flag: "🇺🇸",
    year: 1969,
    shows: 20,
    songs: [
      { name: SONGS.GOOD_TIMES_BAD_TIMES },
      { name: SONGS.COMMUNICATION_BREAKDOWN },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.YOU_SHOOK_ME },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE, isException: true },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.HOW_MANY_MORE_TIMES },

      { name: SONGS.BABE_IM_GONNA_LEAVE_YOU, isException: true },
      { name: SONGS.CMON_EVERYBODY_SOMETHING_ELSE, isException: true },
      { name: SONGS.WHOLE_LOTTA_LOVE, isException: true },
    ],
  },
  {
    id: "db1a04c4",
    name: "UK",
    flag: "🇬🇧",
    year: 1970,
    shows: 8,
    songs: [
      { name: SONGS.WERE_GONNA_GROOVE },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.THANK_YOU },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE, isException: true },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.HOW_MANY_MORE_TIMES },

      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.BRING_IT_ON_HOME, isEncore: true },
      { name: SONGS.LONG_TALL_SALLY, isEncore: true },
      { name: SONGS.CMON_EVERYBODY_SOMETHING_ELSE, isEncore: true },
    ],
  },
  {
    id: "9aa6948d",
    name: "European",
    flag: "🇪🇺",
    year: 1970,
    shows: 16,
    songs: [
      { name: SONGS.WERE_GONNA_GROOVE },
      { name: SONGS.I_CANT_QUIT_YOU_BABY },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.THANK_YOU },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE, isException: true },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.HOW_MANY_MORE_TIMES },

      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.BRING_IT_ON_HOME, isEncore: true },
      { name: SONGS.LONG_TALL_SALLY, isEncore: true },
      { name: SONGS.CMON_EVERYBODY_SOMETHING_ELSE, isEncore: true },
    ],
  },
  {
    id: "72652df6",
    name: "North American Tour Spring",
    flag: "🇺🇸",
    year: 1970,
    shows: 28,
    songs: [
      { name: SONGS.WERE_GONNA_GROOVE },
      { name: SONGS.I_CANT_QUIT_YOU_BABY, isException: true },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.BRING_IT_ON_HOME, isException: true },
      { name: SONGS.WHITE_SUMMER_BLACK_MOUNTAIN_SIDE },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.THANK_YOU },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.HOW_MANY_MORE_TIMES },

      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
    ],
  },
  {
    id: "b149df9d",
    name: "Iceland, Bath and Germany, Summer",
    flag: "🇩🇪",
    year: 1970,
    shows: 6,
    songs: [
      { name: SONGS.IMMIGRANT_SONG },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.BRING_IT_ON_HOME },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.THANK_YOU },
      { name: SONGS.THATS_THE_WAY },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.HOW_MANY_MORE_TIMES, isException: true },

      { name: SONGS.WHOLE_LOTTA_LOVE, isEncore: true },
      { name: SONGS.COMMUNICATION_BREAKDOWN, isEncore: true },
      { name: SONGS.LONG_TALL_SALLY, isEncore: true },
    ],
  },
  {
    id: "153a0a8b",
    name: "North American Summer",
    flag: "🇺🇸",
    year: 1970,
    shows: 25,
    songs: [
      { name: SONGS.IMMIGRANT_SONG },
      { name: SONGS.HEARTBREAKER },
      { name: SONGS.DAZED_AND_CONFUSED },
      { name: SONGS.BRING_IT_ON_HOME },
      { name: SONGS.THATS_THE_WAY },
      { name: SONGS.BRON_YR_AUR },
      { name: SONGS.SINCE_IVE_BEEN_LOVING_YOU },
      { name: SONGS.THANK_YOU },
      { name: SONGS.WHAT_IS_AND_WHAT_SHOULD_NEVER_BE },
      { name: SONGS.MOBY_DICK },
      { name: SONGS.WHOLE_LOTTA_LOVE },

      { name: SONGS.COMMUNICATION_BREAKDOWN },
      { name: SONGS.OUT_ON_THE_TILES },
      { name: SONGS.HOW_MANY_MORE_TIMES },
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: SONGS.BLUEBERRY_HILL },
    ],
  },
];

export default tours;
