const SONGS = {
  TRAIN_KEPT_A_ROLLIN: "Train Kept A-Rollin'",
};

const tours = [
  {
    id: "1c438916",
    name: "Scandinavian",
    flag: "🇩🇰",
    year: 1968,
    number_shows: 14,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "How Many More Times" },
      { name: "White Summer" },
      { name: "For Your Love" },
      { name: "You Shook Me" },
      { name: "Babe I'm Gonna Leave You" },
      { name: "As Long as I Have You" },
      { name: "Communication Breakdown" },
    ],
  },
  {
    id: "4081b991",
    name: "UK",
    flag: "🇬🇧",
    year: 1968,
    number_shows: 16,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: "I Can't Quit You Baby" },
      { name: "As Long as I Have You" },
      { name: "Dazed and Confused" },
      { name: "White Summer" },
      { name: "For Your Love" },
      { name: "You Shook Me" },
      { name: "Pat's Delight" },
      { name: "Babe I'm Gonna Leave You" },
      { name: "How Many More Times" },
      { name: "Communication Breakdown" },
    ],
  },
  {
    id: "d7cd062b",
    name: "North American",
    flag: "🇺🇸",
    year: 1968,
    number_shows: 36,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: "I Can't Quit You Baby" },
      { name: "As Long as I Have You" },
      { name: "Dazed and Confused" },
      { name: "You Shook Me" },
      { name: "White Summer / Black Mountain Side" },
      { name: "Pat's Delight" },
      { name: "Babe I'm Gonna Leave You" },
      { name: "How Many More Times" },
      { name: "Killing Floor" },
      { name: "For Your Love" },
      { name: "Communication Breakdown" },
    ],
  },
  {
    id: "cc92d399",
    name: "UK and Scandinavian",
    flag: "🇬🇧",
    year: 1969,
    number_shows: 33,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: "I Can't Quit You Baby" },
      { name: "I Gotta Move", isException: true },
      { name: "Dazed and Confused" },
      { name: "As Long as I Have You" },
      { name: "Killing Floor" },
      { name: "White Summer / Black Mountain Side" },
      { name: "Babe I'm Gonna Leave You" },
      { name: "You Shook Me" },
      { name: "How Many More Times" },
      { name: "Communication Breakdown" },
      { name: "Pat's Delight" },
    ],
  },
  {
    id: "5bae02b1",
    name: "North American Spring",
    flag: "🇺🇸",
    year: 1969,
    number_shows: 28,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "As Long as I Have You", isException: true },
      { name: "Killing Floor" },
      { name: "White Summer / Black Mountain Side" },
      { name: "Sitting and Thinking", isException: true },
      { name: "Babe I'm Gonna Leave You" },
      { name: "You Shook Me" },
      { name: "How Many More Times" },
      { name: "Communication Breakdown" },
      { name: "Pat's Delight" },
      { name: "Whole Lotta Love", isException: true },
    ],
  },
  {
    id: "2f99abe5",
    name: "UK Summer",
    flag: "🇬🇧",
    year: 1969,
    number_shows: 12,
    songs: [
      { name: SONGS.TRAIN_KEPT_A_ROLLIN },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "As Long as I Have You", isException: true },
      { name: "Killing Floor", isException: true },
      { name: "White Summer / Black Mountain Side" },
      { name: "Babe I'm Gonna Leave You", isException: true },
      { name: "You Shook Me" },
      { name: "Pat's Delight", isException: true },
      { name: "How Many More Times" },
      { name: "Communication Breakdown" },
      { name: "Long Tall Sally", isException: true },
    ],
  },
  {
    id: "f8e69d0a",
    name: "North American Summer",
    flag: "🇺🇸",
    year: 1969,
    number_shows: 46,
    songs: [
      { name: "Train Kept A-Rollin'" },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "You Shook Me" },
      { name: "White Summer / Black Mountain Side" },
      { name: "How Many More Times" },
      { name: "Communication Breakdown" },

      { name: "I Gotta Move", isException: true },
      { name: "What Is and What Should Never Be", isException: true },
      { name: "Pat's Delight", isException: true },
      { name: "Your Time Is Gonna Come", isException: true },
      { name: "Long Tall Sally", isException: true },
    ],
  },

  {
    id: "b3a29330",
    name: "European Autumn",
    flag: "🇪🇺",
    year: 1969,
    number_shows: 5,
    songs: [
      { name: "Good Times Bad Times" },
      { name: "I Can't Quit You Baby" },
      { name: "Heartbreaker", isException: true },
      { name: "Dazed and Confused" },
      { name: "White Summer / Black Mountain Side", isException: true },
      { name: "You Shook Me", isException: true },
      { name: "What Is and What Should Never Be", isException: true },
      { name: "Moby Dick", isException: true },
      { name: "How Many More Times" },
    ],
  },
  {
    id: "66d39321",
    name: "North American Autumn",
    flag: "🇺🇸",
    year: 1969,
    number_shows: 20,
    songs: [
      { name: "Good Times Bad Times" },
      { name: "Communication Breakdown" },
      { name: "I Can't Quit You Baby" },
      { name: "Heartbreaker" },
      { name: "Dazed and Confused" },
      { name: "You Shook Me" },
      { name: "White Summer / Black Mountain Side" },
      { name: "What Is and What Should Never Be", isException: true },
      { name: "Moby Dick" },
      { name: "How Many More Times" },

      { name: "Babe I'm Gonna Leave You", isException: true },
      { name: "C'mon Everybody / Something Else", isException: true },
      { name: "Whole Lotta Love", isException: true },
    ],
  },
  {
    id: "db1a04c4",
    name: "UK",
    flag: "🇬🇧",
    year: 1970,
    number_shows: 8,
    songs: [
      { name: "We're Gonna Groove" },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "Heartbreaker" },
      { name: "White Summer / Black Mountain Side" },
      { name: "Since I've Been Loving You" },
      { name: "Thank You" },
      { name: "What Is and What Should Never Be", isException: true },
      { name: "Moby Dick" },
      { name: "How Many More Times" },

      { name: "Communication Breakdown", isEncore: true },
      { name: "Whole Lotta Love", isEncore: true },
      { name: "Bring It On Home", isEncore: true },
      { name: "Long Tall Sally", isEncore: true },
      { name: "C'mon Everybody / Something Else", isEncore: true },
    ],
  },
  {
    id: "9aa6948d",
    name: "European",
    flag: "🇪🇺",
    year: 1970,
    number_shows: 16,
    songs: [
      { name: "We're Gonna Groove" },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "Heartbreaker" },
      { name: "White Summer / Black Mountain Side" },
      { name: "Since I've Been Loving You" },
      { name: "Thank You" },
      { name: "What Is and What Should Never Be", isException: true },
      { name: "Moby Dick" },
      { name: "How Many More Times" },

      { name: "Communication Breakdown", isEncore: true },
      { name: "Whole Lotta Love", isEncore: true },
      { name: "Bring It On Home", isEncore: true },
      { name: "Long Tall Sally", isEncore: true },
      { name: "C'mon Everybody / Something Else", isEncore: true },
    ],
  },
  {
    id: "72652df6",
    name: "UK",
    flag: "🇺🇸",
    year: 1970,
    number_shows: 28,
    songs: [
      { name: "We're Gonna Groove" },
      { name: "I Can't Quit You Baby", isException: true },
      { name: "Dazed and Confused" },
      { name: "Heartbreaker" },
      { name: "Bring It On Home", isException: true },
      { name: "White Summer / Black Mountain Side" },
      { name: "Since I've Been Loving You" },
      { name: "Organ Solo / Thank You" },
      { name: "What Is and What Should Never Be" },
      { name: "Moby Dick" },
      { name: "How Many More Times" },

      { name: "Whole Lotta Love", isEncore: true },
      { name: "Communication Breakdown", isEncore: true },
    ],
  },
];

export default tours;
