const _ = require("lodash");

const data = [
  {
    name: "Scandinavian Tour",
    flag: "🇩🇰",
    year: 1968,
    number_shows: 14,
    songs: [
      { name: "Train Kept A-Rollin'" },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "How Many More Times" },
      { name: "White Summer" },
      { name: "For Your Love" },
      { name: "You Shook Me" },
      { name: "Babe I'm Gonna Leave You" },
      { name: "As Long as I Have You" },
      { name: "Communication Breakdown" },
    ],
  },
  {
    name: "UK Tour",
    flag: "🇬🇧",
    year: 1968,
    number_shows: 16,
    songs: [
      { name: "Train Kept A-Rollin'" },
      { name: "I Can't Quit You Baby" },
      { name: "As Long as I Have You" },
      { name: "Dazed and Confused" },
      { name: "White Summer" },
      { name: "For Your Love" },
      { name: "You Shook Me" },
      { name: "Pat's Delight" },
      { name: "Babe I'm Gonna Leave You" },
      { name: "How Many More Times" },
      { name: "Communication Breakdown" },
    ],
  },
  {
    name: "North American Tour",
    flag: "🇺🇸",
    year: 1968,
    number_shows: 36,
    songs: [
      { name: "Train Kept A-Rollin'" },
      { name: "I Can't Quit You Baby" },
      { name: "As Long as I Have You" },
      { name: "Dazed and Confused" },
      { name: "You Shook Me" },
      { name: "White Summer / Black Mountain Side" },
      { name: "Pat's Delight" },
      { name: "Babe I'm Gonna Leave You" },
      { name: "How Many More Times" },
      { name: "Killing Floor" },
      { name: "For Your Love" },
      { name: "Communication Breakdown" },
    ],
  },
  {
    name: "UK and Scandinavian Tour",
    flag: "🇬🇧",
    year: 1969,
    number_shows: 33,
    songs: [
      { name: "Train Kept A-Rollin'" },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "As Long as I Have You" },
      { name: "Killing Floor" },
      { name: "White Summer / Black Mountain Side" },
      { name: "Babe I'm Gonna Leave You" },
      { name: "You Shook Me" },
      { name: "How Many More Times" },
      { name: "Communication Breakdown" },
      { name: "Pat's Delight" },
    ],
  },
  {
    name: "North American Tour Spring",
    flag: "🇺🇸",
    year: 1969,
    number_shows: 28,
    songs: [
      { name: "Train Kept A-Rollin'" },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "As Long as I Have You" },
      { name: "Killing Floor" },
      { name: "White Summer / Black Mountain Side" },
      { name: "Babe I'm Gonna Leave You" },
      { name: "You Shook Me" },
      { name: "How Many More Times" },
      { name: "Communication Breakdown" },
      { name: "Pat's Delight" },
      { name: "Whole Lotta Love" },
    ],
  },
  {
    name: "United Kingdom Tour Summer",
    flag: "🇬🇧",
    year: 1969,
    number_shows: 12,
    songs: [
      { name: "Train Kept A-Rollin'" },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "As Long as I Have You" },
      { name: "Killing Floor" },
      { name: "White Summer / Black Mountain Side" },
      { name: "Babe I'm Gonna Leave You" },
      { name: "You Shook Me" },
      { name: "Pat's Delight" },
      { name: "How Many More Times" },
      { name: "Communication Breakdown" },
    ],
  },
  {
    name: "North American Tour Summer",
    flag: "🇺🇸",
    year: 1969,
    number_shows: 46,
    songs: [
      { name: "Train Kept A-Rollin'" },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "You Shook Me" },
      { name: "White Summer / Black Mountain Side" },
      { name: "How Many More Times" },
      { name: "Communication Breakdown" },
    ],
  },

  {
    name: "European Tour Autumn",
    flag: "🇪🇺",
    year: 1969,
    number_shows: 5,
    songs: [
      { name: "Good Times Bad Times" },
      { name: "I Can't Quit You Baby" },
      { name: "Heartbreaker" },
      { name: "Dazed and Confused" },
      { name: "White Summer / Black Mountain Side" },
      { name: "You Shook Me" },
      { name: "What Is and What Should Never Be" },
      { name: "Moby Dick" },
      { name: "How Many More Times" },
    ],
  },
  {
    name: "North American Tour Autumn",
    flag: "🇺🇸",
    year: 1969,
    number_shows: 20,
    songs: [
      { name: "Good Times Bad Times" },
      { name: "Communication Breakdown" },
      { name: "I Can't Quit You Baby" },
      { name: "Heartbreaker" },
      { name: "Dazed and Confused" },
      { name: "You Shook Me" },
      { name: "White Summer / Black Mountain Side" },
      { name: "What Is and What Should Never Be" },
      { name: "Moby Dick" },
      { name: "How Many More Times" },
    ],
  },
  {
    name: "United Kingdom Tour 1970",
    flag: "🇬🇧",
    year: 1970,
    number_shows: 8,
    songs: [
      { name: "We're Gonna Groove" },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "Heartbreaker" },
      { name: "White Summer / Black Mountain Side" },
      { name: "Since I've Been Loving You" },
      { name: "Thank You" },
      { name: "What Is and What Should Never Be" },
      { name: "Moby Dick" },
      { name: "How Many More Times" },
    ],
  },
  {
    name: "European Tour",
    flag: "🇪🇺",
    year: 1970,
    number_shows: 16,
    songs: [
      { name: "We're Gonna Groove" },
      { name: "I Can't Quit You Baby" },
      { name: "Dazed and Confused" },
      { name: "Heartbreaker" },
      { name: "White Summer / Black Mountain Side" },
      { name: "Since I've Been Loving You" },
      { name: "Thank You" },
      { name: "What Is and What Should Never Be" },
      { name: "Moby Dick" },
      { name: "How Many More Times" },
    ],
  },
];

const newVersion = _.map(data, (tour) =>
  tour.songs.map((item) => ({ name: item }))
);

console.log(newVersion);
